image: docker:git
services:
  - docker:dind

stages:
  - test
  - bulid
  - deploy

teste-app:
  stage: test
  image: 
  services:
    - docker:dind
  script:
    - apt install -y python3-mysqldb libmariadb-dev gcc build-essential pkg-config default-libmysqlclient-dev python3-dev
    - pip install -r requirements.txt
    - nosetests --with-xunit --with-coverage --cover-package=project test_users.py
