name: "CIDE - Test"

on:
  pull_request:
    branches:

env: 
  IMAGE_NAME: cicd-demo

jobs:
  test:
    name: "Teste de Aplicação"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix: 
        container:
          - "docker.io/python:3.9-bullseye"
    container:
      image: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4
      - name: "Apt get"
        run: apt update && apt install -y python3-mysqldb libmariadb-dev gcc build-essential pkg-config default-libmysqlclient-dev python3-dev
      - name: "Install pip depends"
        run: pip install -r requirements.txt  
      - name: " Run Test"
        run: nosetests --with-xunit --with-coverage --cover-package=project test_users.py
      - name: Publish Teste Results
        uses: EnricoMI/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            *.xml
  build-container:
    runs-on: ubtuntu-latest
    steps:
    - uses: action/checkout@v4
    - name: "Build Container"
      run: docker build . --file Dockerfile --tag $IAMGE_NAME:${GITHUB_SHA}  






